added variable to display the active scene (PHP-171)
symcon/SzenenSteuerung pull request #18
Opened 2020-12-10 14:34 UTC by TillBrede

2020-12-11 15:12 UTC, DrNiels requested changes

2020-12-11 15:12 UTC, DrNiels commented on SzenenSteuerung/README.md
> +Variablen             | Liste mit den zu schaltenden Variablen
Warum kommen hier die zusätzlichen Leerzeichen?

2020-12-11 15:12 UTC, DrNiels commented on SzenenSteuerung/module.php
> +            IPS_SetVariableProfileAssociation('SZS.SceneControl', 2, $this->Translate('Call'), '', -1);
Warum hast du es von Ausführen zu Aufrufen umbenannt?

2020-12-11 15:12 UTC, DrNiels commented on SzenenSteuerung/module.php
> +        return $sceneID + 1;
$sceneID wird innerhalb der Schleife definiert, du nutzt es aber außerhalb. Auch wenn PHP so einen Schweinkram zulässt, solltest du das noch tun. Außerdem explodiert das ganze sobald du 0 Szenen hast.

2020-12-11 15:12 UTC, DrNiels commented on SzenenSteuerung/module.php
> +                $this->WriteAttributeBoolean('UpdateActive', false);
Wäre das nicht etwas für den Buffer? Oder warum ist das ein Attribut?

2020-12-14 13:18 UTC, TillBrede commented on SzenenSteuerung/module.php
> +            IPS_SetVariableProfileAssociation('SZS.SceneControl', 2, $this->Translate('Call'), '', -1);
Es wurde sich darauf geeinigt, dass 'Aufrufen' für Szenen passender klingt als 'Ausführen'

2020-12-14 13:20 UTC, TillBrede commented on SzenenSteuerung/README.md
> +Variablen             | Liste mit den zu schaltenden Variablen
Das ist ein Überbleibsel einer Änderung, die wieder entfernt wurde.
Kommt weg

2021-01-13 10:28 UTC, DrNiels approved these changes

2021-01-13 10:28 UTC, merged