replaced variableIDs with custom ids (PHP-177)
symcon/SzenenSteuerung pull request #21
Opened 2021-02-09 15:46 UTC by TillBrede

* variables can now be added

2021-02-10 12:54 UTC, DrNiels requested changes

2021-02-10 12:54 UTC, DrNiels commented on SzenenSteuerung/attributes.php
> +
Es fehlt die Definition von Attributes wenn man nicht im Testmodus ist. Hier reicht ein leeres Trait. Fehlt dies, gibt es allerdings einen Fehler beim Erstellen

2021-02-10 12:54 UTC, DrNiels commented on SzenenSteuerung/module.php
> +            IPS_ApplyChanges($this->InstanceID);
Wenn vermeidbar, sollte man nie mit SetProperty und ApplyChanges arbeiten, da die Eigenschaften in der Hoheit des Benutzers liegen. Daher solltest du, wie eigentlich auch abgesprochen, in der Liste eine onAdd-Funktion hinzufügen, welche über UpdateFormField die passende ID setzt.

2021-02-10 12:54 UTC, DrNiels commented on SzenenSteuerung/module.php
> +        $highestID = 0;
Welche Bridge?

2021-02-10 12:54 UTC, DrNiels commented on SzenenSteuerung/form.json
> +        },
Soll die Spalte wirklich sichtbar sein? Ursprünglich hatten wir ja eigentlich gesagt, dass sie das nicht sein soll. Das würde ich auch weiterhin bevorzugen

2021-02-10 12:54 UTC, DrNiels commented on SzenenSteuerung/form.json
> +    }
GetSceneData ist super techy. Es ergibt meiner Meinung nach keinen Sinn diese Funktion im Aktionsbereich anzubieten. Sollte man das wollen, dann müsste man die Ausgabe meiner Meinung nach soweit aufhübschen, dass Standardnutzer damit etwas anfangen können, also so etwas wie:
Szene 1 - "Lampen an":
- Lampe 1: An
- Lampe 2: An
- ...

2021-02-10 12:54 UTC, DrNiels commented on SzenenSteuerung/module.php
> +        //Transfer variableIDs to IDs
Woher weißt du, ob diese Anpassung überhaupt notwendig ist? Wenn deine numerischen IDs weit ansteigen, beispielsweise via wiederholtem Hinzufügen und Entfernen von Variablen, dann könntest du hier IDs fälschlicherweise ersetzen! Die Differenzierung wäre übrigens trivial, wenn du wie ursprünglich vorgeschlagen GUIDs verwenden würdest.

2021-02-10 12:54 UTC, DrNiels commented on SzenenSteuerung/module.php
> +        }
Du kannst $scene mit einem & referenzieren, dann kannst du direkt auf $scene arbeiten und musst nicht über den Index gehen. Die genaue Notation dafür habe ich allerdings nicht parat, da müsstest du mal kurz recherchieren.

2021-02-10 12:54 UTC, DrNiels commented on SzenenSteuerung/module.php
> +        //Remove unused ids form SceneData
form -> from

2021-02-10 12:54 UTC, DrNiels commented on SzenenSteuerung/module.php
> +        $targets = json_decode($this->ReadPropertyString('Targets'), true);
Belege Variablen nicht doppelt! Hier kannst du (zumindest in der aktuellen Struktur, ggfs. musst du in der Überarbeitung mal schauen) einfach die $targets aus Zeile 126 wiederverwenden.

2021-02-10 12:54 UTC, DrNiels commented on SzenenSteuerung/module.php
> +        $scenes = json_decode($this->ReadAttributeString('SceneData'), true);
Hier kannst du analog zum Kommentar aus Zeile 144 die $scenes aus Zeile 131 wiederverwenden

2021-02-10 12:54 UTC, DrNiels commented on SzenenSteuerung/module.php
> +            }
Siehe Kommentar aus Zeile 132ff

2021-02-10 12:54 UTC, DrNiels commented on SzenenSteuerung/module.php
> +            foreach ($scenes[$i] as $guid => $value) {
Aktuell hast du das gar nicht als GUID implementiert, dann sollte die Variable auch nicht so heißen

2021-02-10 12:54 UTC, DrNiels commented on SzenenSteuerung/module.php
> +                $id = $this->getVariable($guid);
Hier fliegen so viele IDs rum, wie wäre es mit $variableID?

2021-09-06 13:35 UTC, DrNiels requested changes
Ist die Aktive Szene Unbekannt und wird eine Szene gespeichert, dann wäre es nett, das Unbekannt zu aktualisieren auf die gerade gespeicherte Szene.

Ansonsten sieht das aber gut aus!

2021-09-06 13:35 UTC, DrNiels commented on SzenenSteuerung/form.json
> -    },
Wenn das rausfliegt, gerne den NumberSpinner dafür verbessern, z.B. ausführlichere Caption und suffix

2021-09-06 13:35 UTC, DrNiels commented on SzenenSteuerung/module.php
> +        unset($target);
Mach da mal lieber die "Mischu-Variante" und mache ein foreach ($targets as $index => $target)

Das unset versteht sonst niemand ;)

Da war mein ursprünglicher Kommentar wohl doch nicht so zielführend wie ich dachte...

2022-03-10 08:50 UTC, DrNiels requested changes
- Ich konfiguriere eine Szenensteuerung mit 2 Variablen -> Änderungen übernehmen
- Entferne die erste Variable, füge eine andere Variable hinzu -> Änderungen übernehmen
- Die neu hinzugefügte Variable verschwindet! Das sollte sie nicht tun

2022-03-16 09:24 UTC, TillBrede commented
![image](https://user-images.githubusercontent.com/51406030/158557237-7e4b458b-2c68-472a-877c-c2bef760506f.png)
Es sieht so aus, als würden nicht alle in der Liste angezeigten Elemente auch übertragen werden.

2022-03-16 13:01 UTC, DrNiels approved these changes
Fehler war in Konsole und nicht im Modul. Fix ist bereits unterwegs

2022-03-16 13:01 UTC, merged