Feature/list (based on the attributes PR#2)
symcon/SzenenSteuerung pull request #3
Opened 2019-08-05 08:07 UTC by TillBrede

2019-08-05 08:08 UTC, TillBrede commented
based on PR #2

2019-08-06 08:25 UTC, paresy requested changes

2019-08-06 08:25 UTC, paresy commented on SzenenSteuerung/module.php
> +		$this->RegisterPropertyString("VariablesToSwitch", "[]");
falsche Position. Properties sind zwei Zeilen höher

2019-08-06 08:25 UTC, paresy commented on SzenenSteuerung/form.json
> +      "name": "VariablesToSwitch",
Wollen wir dies nicht lieber **Targets** nennen, wie es vorher war?

2019-08-06 09:31 UTC, merged